### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by yogeshVU** [geerlingguy/docker-ubuntu1604-ansible#2]
I tried to create a container as per the README and run it on my Ubuntu 14.04 machine. I get following error

```
$ docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro systemd16_geer /usr/lib/systemd/systemd
WARNING: Error loading config file:/home/vagrant/.docker/config.json - stat /home/vagrant/.docker/config.json: permission denied
afbea0f43e462f206f4889f331f6567c8cea8d2d02cc846ea4bcb27be2fedc36
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/lib/systemd/systemd\": stat /usr/lib/systemd/systemd: no such file or directory".
```

**Comment by yogeshVU** [comment]
rather than /usr/lib/system/system I passed /sbin/init and it worked.

**Comment by geerlingguy** [comment]
Sorry about that! The path is actually `/lib/systemd/systemd`, don't know why I had the wrong thing in the README. Thanks for the report—fixed via above commit.

**Comment by yogeshVU** [comment]
Thanks!. Is there away to run the systemd container without running first in the detach mode and then running ansible-playbook using the exec method? 
Can one directly instantiate ansible-playbook command to the Ubuntu:16.04 (systemd)container like:

`docker run -it Systemd_Ubuntu:16.04 ansible-playbook main.yml`

**Comment by geerlingguy** [comment]
@yogeshVU - Sort of... you would probably need to create a Dockerfile to configure things so the playbook would run on container start. Otherwise if you use `-it`, a volume (`-v`) to share the playbook into the container, and the command to run it may just work (I haven't tested.)
