### ISSUE TITLE
Missing iproute2 causes ansible_default_ipv4 to be empty

### ISSUE THREAD

**Issue by jaredledvina** [geerlingguy/docker-ubuntu1604-ansible#5]
I've been attempting to sort out why my Ubuntu 16.04 tests are failing due to `ansible_default_ipv4` not being defined. I tracked this down to the fact that this fact uses the command `ip -4 route get 8.8.8.8` here https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/network/linux.py#L71 

However, it looks like the base ubuntu:16.04 image does not ship with iproute2 installed:
```
root@265e6d2b2383:/# ip -4 route get 8.8.8.8
bash: ip: command not found
```
```
root@265e6d2b2383:/# ansible localhost -m setup  | grep ansible_default_ipv4
root@265e6d2b2383:/#
```
@geerlingguy - Would it be fair to include that package in this image?

**Comment by geerlingguy** [comment]
Merged after rebase, thanks!
